export type FirebaseErrorMessagePair = {
  key: string
  value: string
}

export const authErrors = [
  { key: "auth/network-request-failed", value: "A network error has occurred, please try again later." },
  { key: "auth/claims-too-large", value: "The claims payload provided exceeds the maximum allowed size of 1000 bytes." },
  { key: "auth/email-already-exists", value: "The provided email is already in use." },
  { key: "auth/id-token-expired", value: "The Firebase ID token is expired." },
  { key: "auth/id-token-revoked", value: "The Firebase ID token has been revoked." },
  { key: "auth/insufficient-permission", value: "The credential used to initialize the Admin SDK has insufficient permission to access the requested Authentication resource." },
  { key: "auth/internal-error", value: "The Authentication server encountered an unexpected error while trying to process the request." },
  { key: "auth/invalid-argument", value: "An invalid argument was provided to an Authentication method." },
  { key: "auth/invalid-claims", value: "The custom claim attributes provided are invalid." },
  { key: "auth/invalid-continue-uri", value: "The continue URL must be a valid URL string." },
  { key: "auth/invalid-creation-time", value: "The creation time must be a valid UTC date string." },
  { key: "auth/invalid-credential", value: "The credential used to authenticate the Admin SDKs cannot be used to perform the desired action." },
  { key: "auth/invalid-disabled-field", value: "The provided value for the disabled user property is invalid. It must be a boolean." },
  { key: "auth/invalid-display-name", value: "The provided value for the displayName user property is invalid. It must be a non-empty string." },
  { key: "auth/invalid-dynamic-link-domain", value: "The provided dynamic link domain is not configured or authorized for the current project." },
  { key: "auth/invalid-email", value: "The provided value for the email user property is invalid. It must be a string email address." },
  { key: "auth/invalid-email-verified", value: "The provided value for the emailVerified user property is invalid. It must be a boolean." },
  { key: "auth/invalid-hash-algorithm", value: "The hash algorithm must match one of the strings in the list of supported algorithms." },
  { key: "auth/invalid-hash-block-size", value: "The hash block size must be a valid number." },
  { key: "auth/invalid-hash-derived-key-length", value: "The hash derived key length must be a valid number." },
  { key: "auth/invalid-hash-key", value: "The hash key must a valid byte buffer." },
  { key: "auth/invalid-hash-memory-cost", value: "The hash memory cost must be a valid number." },
  { key: "auth/invalid-hash-parallelization", value: "The hash parallelization must be a valid number." },
  { key: "auth/invalid-hash-rounds", value: "The hash rounds must be a valid number." },
  { key: "auth/invalid-hash-salt-separator", value: "The hashing algorithm salt separator field must be a valid byte buffer." },
  { key: "auth/invalid-id-token", value: "The provided ID token is not a valid Firebase ID token." },
  { key: "auth/invalid-last-sign-in-time", value: "The last sign-in time must be a valid UTC date string." },
  { key: "auth/invalid-page-token", value: "The provided next page token in listUsers() is invalid. It must be a valid non-empty string." },
  { key: "auth/invalid-password", value: "The provided value for the password user property is invalid. It must be a string with at least six characters." },
  { key: "auth/invalid-password-hash", value: "The password hash must be a valid byte buffer." },
  { key: "auth/invalid-password-salt", value: "The password salt must be a valid byte buffer" },
  { key: "auth/invalid-phone-number", value: "The provided value for the phoneNumber is invalid. It must be a non-empty E.164 standard compliant identifier string." },
  { key: "auth/invalid-photo-url", value: "The provided value for the photoURL user property is invalid. It must be a string URL." },
  { key: "auth/invalid-provider-data", value: "The providerData must be a valid array of UserInfo objects." },
  { key: "auth/invalid-provider-id", value: "The providerId must be a valid supported provider identifier string." },
  { key: "auth/invalid-oauth-responsetype", value: "Only exactly one OAuth responseType should be set to true." },
  { key: "auth/invalid-session-cookie-duration", value: "The session cookie duration must be a valid number in milliseconds between 5 minutes and 2 weeks." },
  { key: "auth/invalid-uid", value: "The provided uid must be a non-empty string with at most 128 characters." },
  { key: "auth/invalid-user-import", value: "The user record to import is invalid." },
  { key: "auth/maximum-user-count-exceeded", value: "The maximum allowed number of users to import has been exceeded." },
  { key: "auth/missing-android-pkg-name", value: "An Android Package Name must be provided if the Android App is required to be installed." },
  { key: "auth/missing-continue-uri", value: "A valid continue URL must be provided in the request." },
  { key: "auth/missing-hash-algorithm", value: "Importing users with password hashes requires that the hashing algorithm and its parameters be provided." },
  { key: "auth/missing-ios-bundle-id", value: "The request is missing a Bundle ID." },
  { key: "auth/missing-uid", value: "A uid identifier is required for the current operation." },
  { key: "auth/missing-oauth-client-secret", value: "The OAuth configuration client secret is required to enable OIDC code flow." },
  { key: "auth/operation-not-allowed", value: "The provided sign-in provider is disabled for your Firebase project." },
  { key: "auth/phone-number-already-exists", value: "The provided phoneNumber is already in use by an existing user." },
  { key: "auth/project-not-found", value: "No Firebase project was found for the credential used to initialize the Admin SDKs."},
  { key: "auth/reserved-claims", value: "One or more custom user claims provided to setCustomUserClaims() are reserved."},
  { key: "auth/session-cookie-expired", value: "The provided Firebase session cookie is expired." },
  { key: "auth/session-cookie-revoked", value: "The Firebase session cookie has been revoked." },
  { key: "auth/too-many-requests", value: "The number of requests exceeds the maximum allowed." },
  { key: "auth/uid-already-exists", value: "The provided uid is already in use by an existing user." },
  { key: "auth/unauthorized-continue-uri", value: "The domain of the continue URL is not whitelisted." },
  { key: "auth/user-not-found", value: "There is no existing user record corresponding to the provided identifier." },
]